<?php

namespace BlogBundle\Entity\Forms;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class Authorization extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'login', TextType::class, ['label' => 'Login: ',]
        )->add(
            'pswd', TextType::class, ['label' => 'Password: ',]
        )->add(
            'Authorization', SubmitType::class, []
        );

        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }
}

class Register extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'login', TextType::class, ['label' => 'Login: ',]
        )->add(
            'pswd', TextType::class, ['label' => 'Password: ',]
        )->add(
            'name_user', TextType::class, ['label' => 'Name: ',]
        )->add('Registration', SubmitType::class);
    }
}