homepage:
    path: /
    defaults: { _controller: BlogBundle:Post:homepage }

blog_view:
    path: /blog/{id}
    defaults: { _controller: BlogBundle:Post:viewBlog }
    requirements:
      id: \d+

authorization:
    path: /authorization
    defaults: { _controller: BlogBundle:Users:authorization }